### ISSUE TITLE
Citation / Works UI designs

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/rp-ucd-client#10]

**Comment by wrenaria** [comment]
# Publications Citation List

Citations are grouped by **Category** (example: Academic Articles, Chapters) and then by **Year** (2020).

**Individual citations display information in this order:**
Publication Name [linked to full publication info page]. Authors [last name followed by first initial(s), no commas/punctuation within the names; examples: Adaska JM, Ekong PS]. Journal Name. Location in Journal. 

### Citation List Display Rules
Since items are split out by type, "show X more" / "show X less" buttons seem like the best solution for managing long publication lists (if they weren't, I'd probably favor paging). "Show X less" only appears once "show X more" has been clicked at least once.

I would like it to be so that if the author only has publications that fall into one category (e.g., academic articles), 10 articles are shown by default. If the author has publications spanning multiple categories (e.g., academic articles, chapters, conference papers) then show a max of 5 per category to keep the publications block from becoming overwhelmingly long. TLDR: 

**1 publication category = 10 citations displayed
Multiple publication categories = 5 citations displayed per category**

No matter the number of categories an author has published in, the "show more" button will always show 10 more articles (or whatever number remains if there are less than 10). 

### Show More/Less buttons:
![Screen Shot 2020-09-25 at 11 04 57 AM](https://user-images.githubusercontent.com/17831969/94301163-facc0d80-ff1e-11ea-9ef9-b63ccba7a007.png)

### Publications in context:
Text format stays the same all the way down to mobile scales.

![Screen Shot 2020-09-25 at 11 16 21 AM](https://user-images.githubusercontent.com/17831969/94302153-9dd15700-ff20-11ea-8c11-0bf15ec086df.png)

![Screen Shot 2020-09-25 at 11 19 00 AM](https://user-images.githubusercontent.com/17831969/94302347-f0ab0e80-ff20-11ea-9d34-a7bc1e49537f.png)

# Individual Works Page
Links to full text and metrics appear on the individual work's information page. Metrics links only appear on publications for which the logged in user has authored, otherwise that section is hidden. See last image of this comment for notes on individual components of this page. 

### Logged in:
Citation Data and Metrics links only appear for the author of a publication. 

![Web 1920 – Publication Page](https://user-images.githubusercontent.com/17831969/94305718-81381d80-ff26-11ea-8533-19c16adedc8f.png)


### Not logged in: 
Citation Data and Metrics info is hidden.

![Screen Shot 2020-09-25 at 11 54 10 AM](https://user-images.githubusercontent.com/17831969/94305467-10910100-ff26-11ea-83ec-8e374892c707.png)

### Annotated: 

![Web 1920 – Publication Page Anno](https://user-images.githubusercontent.com/17831969/94305722-839a7780-ff26-11ea-838f-6f6aaa5b08c2.png)

**Comment by Vensberg** [comment]
The UC eLinks should be UCD-eLinks to match the button display and emphasize the Davis Library (rather than general UC).
