### ISSUE TITLE
Edit icons

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/rp-ucd-client#164]
An edit icon next to the "Positions" field should take users here: https://org.ucdavis.edu/odr/.
An edit icon next to "Research areas" field should take users to the Elements section on Fields of Research.

**Comment by jrmerz** [comment]
@qjhart this issue requires that we have the elements UID.  See here: https://github.com/ucd-library/vessel/issues/27.  Please let us know if that's possible to add to harvest data.

**Comment by jrmerz** [comment]
needs to match #75  design

**Comment by Vensberg** [comment]
Looks good to me. Leaving for @wrenaria to sign off.

**Comment by wrenaria** [comment]
I have some concerns  --

1. Hover text is needed on both buttons: "Edit Keywords" and "Edit Positions". This will make them consistent with the other editing buttons. Users have also consistently checked for hover text on other editing buttons before clicking on them in user testing. They like the confirmation that it's what they are after.  

2. Looks like the Edit Keywords button goes straight to UC Publication Management without displaying the instructions pop-up. I think the pop-up from issue #75 will be helpful for people to understand what they are supposed to do after they are redirected, so it would be best if we could include that.

3. After clicking Edit Keywords and signing into UCPM, I get this error:
![Screen Shot 2021-04-15 at 11 46 45 AM](https://user-images.githubusercontent.com/17831969/114922727-dcf1c780-9de0-11eb-867e-7a17bd652dae.png)
Is this because I am not actually the user I am impersonating, or some other problem? Is it an everyone problem, or a me problem?

**Comment by jrmerz** [comment]
@wrenaria Issues 1 and 2 above are implemented (deploying now).  Issue 3, I'd say there is a 99% chance the  impersonating user functionality won't work with that link to elements.  I tried the link myself and it worked fine.

**Comment by wrenaria** [comment]
Not quite there, but almost!

1. Remove quotation marks in all the editing pop-up titles 
2. People need to know _where_ in UCPM to edit their keywords (as shown in issue #75). I copied the text over and edited it down a little bit base on where the user actually lands on log in to UCPM:

### Text for the pop-up:
```
Edit Keywords
Keywords are managed via the “Fields of Research” section of your UC Publication Management System profile. Clicking the “Edit Keywords” button below will redirect you to the UC Publication Management System. Any changes made there will be reflected on your Aggie Experts profile. 

Steps to Add/Delete Keywords:
1. In the "About" block, select the “Edit” button located just to the right of the “Fields of Research” label.
2. To add keywords, search for and select a subject from “Available values.” To remove keywords, select an item from the “Your Selection” list.
3. Select “Save” to confirm your changes.
```
And how it should look:
![Screen Shot 2021-04-16 at 12 06 11 PM](https://user-images.githubusercontent.com/17831969/115072212-24915580-9eac-11eb-84bb-219c0184d127.png)

**Comment by Vensberg** [comment]
I am having the same problem as Kimmy.

**Comment by Vensberg** [comment]
Also, let's have the window go away once the user is taken to the new tab.

**Comment by jrmerz** [comment]
@Vensberg which part of Kimmy's discussion are you referring to?

**Comment by jrmerz** [comment]
Are you impersonating someone?
