### ISSUE TITLE
Websites and publisher ids

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/rp-ucd-client#220]
Currently publisher ids are featured under websites. We are about to bring in lab website urls, and eventually researchers may want to add twitter accounts there. Should the two types of links be shown in the same field or in separate field (which would then need to be designed)?

**Comment by wrenaria** [comment]
Websites will remain as one list, with icons. 

![ae-websites](https://user-images.githubusercontent.com/17831969/119394419-ff4fee00-bc86-11eb-855a-4cac49434fe4.png)

The website icon is the same font awesome icon that campus uses int he new brand. I uploaded it as svg here: https://drive.google.com/file/d/1YmtSRW_GQ7LxmoT8TsVzfpn6QG2W9oQN/view?usp=sharing 

Social icons: https://drive.google.com/drive/folders/1mLFV0m14UmTcRXsSMMu6LYnrcL90IocQ?usp=sharing 

These "Academicons" might also be helpful: https://jpswalsh.github.io/academicons/

**Comment by qjhart** [comment]
When URL data comes in from the elements system, we have a setup that looks like this: 

![image](https://user-images.githubusercontent.com/344953/122991533-fd4a7f00-d359-11eb-930e-22859925d1c9.png)

Where we have a well-known type, a label and a URL.  The VIVO [Person](https://wiki.lyrasis.org/display/VIVODOC111x/Person+Model) implementation would suggest that these associations are sent to the OAP derived vcard.  Currently, we don't use the OAP vcard, because the title and name are superseded by the IAM.  Adding the websites here would require that the client discovers these in the OAP-1 vcard.   The above image would look something like: 

```ttl
person:f9ef1e530c617cd598171497b4a49e82
        a                     ucdrp:person , foaf:Person ;
        rdfs:label            "Quinn Hart" ;
        obo:ARG_2000028       <http://experts.ucdavis.edu/person/f9ef1e530c617cd598171497b4a49e82#vcard> ;
        .

<http://experts.ucdavis.edu/person/f9ef1e530c617cd598171497b4a49e82#vcard>
        a                 vcard:Individual ;
        ucdrp:identifier  "oap-1" ;
        vcard:hasURL      <http://experts.ucdavis.edu/person/f9ef1e530c617cd598171497b4a49e82#vcard-url-1> , <http://experts.ucdavis.edu/person/f9ef1e530c617cd598171497b4a49e82#vcard-url-0> .


<http://experts.ucdavis.edu/person/f9ef1e530c617cd598171497b4a49e82#vcard-url-1>
        a              vcard:URL ;
        rdfs:label     "Evaporation (Meteorology)" ;
        ucdrp:urlType  ucdrp:UrlType_other ;
        vivo:rank      1 ;
        vcard:url      "http://id.worldcat.org/fast/917080" .


<http://experts.ucdavis.edu/person/f9ef1e530c617cd598171497b4a49e82#vcard-url-0>
        a              vcard:URL ;
        rdfs:label     "Quinn Hart" ;
        ucdrp:urlType  ucdrp:UrlType_googlescholar ;
        vivo:rank      0 ;
        vcard:url      "https://scholar.google.com/citations?user=Od5weOkAAAAJ&hl=en&oi=ao" .

```

Where we've added a `ucdrp:urlType` to specify the types in elements.
