### ISSUE TITLE
Unlabeled website in the About section

### ISSUE THREAD

**Issue by Vensberg** [ucd-library/rp-ucd-client#338]

**Comment by Vensberg** [comment]
https://rc.experts.ucdavis.edu/person/f9ef1e530c617cd598171497b4a49e82
<img width="448" alt="missing website label" src="https://user-images.githubusercontent.com/26015534/164552553-354d7533-986b-4e05-97e7-9dd8a99af735.png">

**Comment by Vensberg** [comment]
Are there others?

**Comment by UcDust** [comment]
Hi @Vensberg, it looks like this is a small bug in the function that gets the websites for a person, it had a hardcoded schema prefix/alias of `experts:`, but on RC there's an global config file that has it defined as `ucdrp:`. We can adjust the code to reference the global config file to fix this, and also add a bit of safety precautions in the code, so that if there is no label, the label will just show as the url. We can pull this into this sprint.

**Comment by Vensberg** [comment]
Sounds like a good fix for now. We may run into problems if the url is too long, and we'll need @wrenaria to look at that when it happens. Maybe we can apply a generic label like "website".
I just realized that this url is the same as the one fully listed on the left. Do we check for redundancies?

**Comment by UcDust** [comment]
We could apply a generic 'Website' label if they don't have their own label instead of showing the full url, would you like do to that?

It doesn't look like there is a check for redundancies, but in Quinn's case (and probably others), it takes the user websites and gets the top ranked it looks like. So after the fix, he won't have a duplicate link under both Roles and Websites. Would you like to work in some redundancy checks?

**Comment by wrenaria** [comment]
Please **don't** use a generic website label. It is not enough information for the user to know where they are going offsite, especially if there end up being multiple URLs that show up as "website" in the list. It would be a very frustrating experience for people.

If long URLs are truly a persistent problem, you could maybe just show the core URL so there's at least a hint of where they are going. For example, instead of "library.ucdavis.edu/author/quinn-hart" show "library.ucdavis.edu" I'd rather risk people thinking that are just going to the base site (as opposed to the subpage url) than to know nothing about where a link is taking them.

That said, if most URLs are as short as the example URL I used above, then I'd rather just show the whole thing like we currently do under Roles.

**Comment by wrenaria** [comment]
Also: I am in favor of checking for and removing redundancies!

When there is a duplicate, I think favor keeping the one on "roles" and remove the duplicate from the "website" list?

**Comment by Vensberg** [comment]
That makes sense to me.

**Comment by UcDust** [comment]
Will do, thanks for the input.

**Comment by UcDust** [comment]
Chatted with @qjhart more on this, we added some code to remove duplicates if they come up, and if the website doesn't have a label it should get a label as the full url. If there are no websites then the _Websites_ section will not show up (this is pre-existing behavior).

**Comment by Vensberg** [comment]
@qjhart can you pull data for your profile on dev from Production Elements (currently the data are from QA)

**Comment by Vensberg** [comment]
Redundancy removing worked.
