### ISSUE TITLE
Implement mobile break points

### ISSUE THREAD

**Issue by jrmerz** [ucd-library/rp-ucd-client#63]
Add correct breakpoints and adjusted padding for mobile. Sub #47

**Comment by wrenaria** [comment]
### Style Adjustments
- Search box is breaking mobile viewport on homepage
- Top sections of the individual people/subject/work info pages + search results page should be full width when the viewport is < max width of content area.
- Not mobile-specific (and maybe this should be split into its own issue?) but the text on search results pages seems more spread out than elsewhere in site. Wondering if line-height is different/messed up somehow?

Search Results | People/Subject/Work Info Pages
--- | ---
![Screenshot_20210127-113850_Chrome](https://user-images.githubusercontent.com/17831969/106065912-d345a700-60b0-11eb-86b5-a76643f85ea8.jpg) | ![Screenshot_20210127-115745_Chrome](https://user-images.githubusercontent.com/17831969/106065934-d9d41e80-60b0-11eb-8977-e8179a7f5373.jpg)

### Is this possible?
Is it possible control icon alignment based on either # of text lines or content height? 

Because item icons looks kind of weird when center-aligned on items with lots of text and is then better when top-aligned, but when there's not a lot of text, it looks super weird if it's not centered. Essentially I am asking:

![IconAlignment](https://user-images.githubusercontent.com/17831969/106064377-97114700-60ae-11eb-9fbf-1e1aadd7bf2d.png)

If not, we can leave as is. Centered icons on lots of text is less visually offensive to me than when the icon is top-aligned to minimal text in this context.

**Comment by spelkey-ucd** [comment]
@wrenaria whats the px threshold for making the top section 100% viewport width? 480px?

**Comment by spelkey-ucd** [comment]
@wrenaria after re-reading your comments, i see max-content width should be the threshold. so 970px?

**Comment by wrenaria** [comment]
@spelkey-ucd Correct.

**Comment by spelkey-ucd** [comment]
@wrenaria adjustments made.

Re, line height. it was set to 1.625 of the default text pixel size (16). So anything with 14px font seemed wider. I changed the base rule to be just plain 1.625. Soooo some other line heights might look a little different. let me know if further adjustments are needed.

**Comment by wrenaria** [comment]
@spelkey-ucd OH MY GOD the line-height and icon changes made such a huge difference. Looks great!

Looks like one change is missing: The search results top section should be full width sub-970px. I'm still seeing margins there.

**Comment by spelkey-ucd** [comment]
ahh yes forgot about search
