### ISSUE TITLE
Implement Mobile Hamburger Menu

### ISSUE THREAD

**Issue by spelkey-ucd** [ucd-library/rp-ucd-client#71]
https://drive.google.com/drive/folders/1yjwMrc1nu1jll7zFB9RM977NIoCGK_h5

**Comment by wrenaria** [comment]
There's a few things to adjust:
- Need to indicate that the mobile menu is open. The hamburger should shift into an X (see [library](https://www.library.ucdavis.edu/) or [ucdavis](https://www.ucdavis.edu/) menus) 
-- _I realize this is my bad, looks like I accidentally left it out of the mockup. Sorry!_
- The search bar is breaking the viewport. Not good. (This is happing on homepage too)
- Need a link to "Home" page at top of link list. 
- The "Hello" should be "Hello Firstname Lastname!" (as displayed on profile) and not "Hello KerberosUsername!"

Otherwise, styling looks good. 

Screenshot from my phone:

<img src="https://user-images.githubusercontent.com/17831969/106042275-ae8e0700-6091-11eb-8504-800cab36dd54.jpg" width="300" >

**Comment by spelkey-ucd** [comment]
Currently, we aren't pulling through the name of the signed in individual - just their username.

I'm gonna move that aspect of your comment to a new issue.
